name: SimpMusic
options:
  bundleIdPrefix: com.maxrave.simpmusic
targets:
  SimpMusic:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources: [iosApp]
    info:
      path: iosApp/Info.plist
    settings:
      base:
        PRODUCT_NAME: SimpMusic
        INFOPLIST_KEY_CFBundleDisplayName: SimpMusic
        INFOPLIST_KEY_CFBundleName: SimpMusic
        ENABLE_PREVIEWS: YES
        ENABLE_BITCODE: NO
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      configs:
        Debug:
          ENABLE_TESTABILITY: YES
